### ISSUE TITLE
Long Titles Not Properly Displayed

### ISSUE THREAD

**Issue by rjm001** [elauksap/focus-beamertheme#2]
Great theme! But, long titles don't get displayed properly. Can make title space automatically adjust to be longer if necessary?

Consider this presentation with a long title. The title gets cut off.

![focusthemetitletoobig](https://user-images.githubusercontent.com/20239878/46255110-24482080-c44e-11e8-9833-a1de2aacec62.PNG)

\documentclass[]{beamer}
\usetheme[nofirafonts]{focus}

\title{ A Practical Approach to Evolutionarily Stable Solution Concepts in Dynamic Network Games with Unobserved Heterogeneity Under Uncertainty }
\author{Author}

\begin{document}
	\maketitle

\end{document}

**Comment by elauksap** [comment]
Hi rjm001,

thanks for using Focus!

It's not recommended to have such a long title. By design choices, the template definition requires that the title is shorter than three lines.

If you are still looking for a solution to insert a very long title, I would recommend to manually set its size so that it becomes more easily readable. This is done with a command like:

`latex
\title{{\Large My very long title}}
`

**Comment by pcafrica** [comment]
Hi rjm001,

thanks for using Focus!

It's not recommended to have such a long title. By design choices, the template definition requires that the title is shorter than three lines.

If you are still looking for a solution to insert a very long title, I'd rather suggest to manually set its size so that it becomes more easily readable. This is done with a command like:

`
\title{{\Large My very long title}}
`
