### ISSUE TITLE
Frame header and noframenumbering

### ISSUE THREAD

**Issue by thistlillo** [elauksap/focus-beamertheme#30]
Hello I am using focus on overleaf and have an issue with the frame numbering.

I would like to add a "normal" frame titled "Outline", but I do not want to number this frame. With the current version it seems that:
- if I add the option `noframenumbering`, then the frame/slides has no header. In this case, the title "Outline" is not printed out.
- if I want the header, in this case "Outline", I must accept the frame number.

Is this the expected behaviour?

**Comment by pcafrica** [comment]
Can you provide a minimal working example to reproduce the issue, please?

Best.



-------- Original message --------
From: Franco Alberto Cardillo ***@***.***>
Date: 4/25/24 18:01 (GMT+01:00)
To: pcafrica/focus-beamertheme ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pcafrica/focus-beamertheme] Frame header and noframenumbering (Issue #30)


Hello I am using focus on overleaf and have an issue with the frame numbering.

I would like to add a "normal" frame titled "Outline", but I do not want to number this frame. With the current version it seems that:

  *   if I add the option noframenumbering, then the frame/slides has no header
  *   if I want the header, in this case "Outline", I must accept the frame number.

Is this the expected behaviour?

**Comment by pcafrica** [comment]
The following example from the demo seems to work correctly:

```
\begin{frame}[noframenumbering]{No frame numbering}
    This frame is not numbered but has a title.
\end{frame}
```

Please make sure you are using the latest release v3.4.0 of Focus.

Feel free to re-open the issue if needed.

Best,
Pasquale
