### ISSUE TITLE
Without sections, the `\frametitle` on the first content slide doesn't get shown

### ISSUE THREAD

**Issue by Asqiir** [elauksap/focus-beamertheme#33]
I have a presentation that does not uses `\section{}` at all.
On the first slide after the titlepage, the frametitle is missing.

If I use a section, I get a slide after the titlepage inserted that I do not want.

## Expected behaviour
not omitting any frametitle, but working fine without sections

**Comment by pcafrica** [comment]
Hi @Asqiir,

the issue is not reproducible with the latest version of Focus.

This is what I get with the following MWE:
[focus-demo.pdf](https://github.com/user-attachments/files/17085636/focus-demo.pdf)

Code:
```tex
% !TeX TS-program = xelatex

\documentclass{beamer}
\usetheme[nofirafonts]{focus}

\title{Focus: \\ A Minimalist Beamer Theme}
\subtitle{Subtitle}
\author{Author 1\texorpdfstring{\\}{,} Author 2}
\titlegraphic{\includegraphics[scale=1.25]{focus-logo.pdf}}
\institute{Institute Name \\ Institute Address}
\date{dd mm yyyy}

\begin{document}
    \begin{frame}
        \maketitle
    \end{frame}
    
    \begin{frame}{Simple frame}
        This is a simple frame.
    \end{frame}

    \begin{frame}{Simple frame}
		This is a simple frame.
	\end{frame}
\end{document}
```

Please make sure you are using the current release.

Feel free to reopen this issue in case the problem persists.

Best.

**Comment by Asqiir** [comment]
Hi, the issue only exists with `\frame{\titlepage}`, but not with

```latex
\begin{frame}
  \maketitle
\end{frame}
```

**Comment by pcafrica** [comment]
If you use `\frame{...}` instead of `\begin{frame}...\end{frame}` some counters will not get the correct value and some templates will not be properly set (see [here](https://github.com/pcafrica/focus-beamertheme/blob/main/beamerouterthemefocus.sty#L242)).

In recent versions of Beamer the use of `\frame{...}` is discouraged and provided only to support legacy documents, as stated in the [official Beamer user guide](https://tug.ctan.org/macros/latex/contrib/beamer/doc/beameruserguide.pdf).

Hope this helps!

Best.
